version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "8000:8000"
    command: "uvicorn --factory app.application.main:get_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app:/app/app
    networks:
      - backend

networks:
  backend:
    driver: bridge