name: test-cd
on:
  push:
    branches: [master, refactoring]
  pull_request:
    branches: [master]
    
jobs:
  my-test-cd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: run a one line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
            echo Add other actions to build,
            echo test, and deploy your project.
